# Generated by Django 5.1.7 on 2025-03-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchlistAPI", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="release_date",
            field=models.DateField(),
        ),
    ]
