# Generated by Django 5.1.7 on 2025-03-22 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchlistAPI", "0002_alter_watchlist_release_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchcategory",
            name="name",
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watchlist",
                to="watchlistAPI.watchcategory",
            ),
        ),
    ]
